# Generated by Django 5.2.10 on 2026-02-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='user',
            name='location_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_author',
            field=models.BooleanField(default=False, verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_editor',
            field=models.BooleanField(default=False, verbose_name='Éditeur'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_reader',
            field=models.BooleanField(default=True, verbose_name='Lecteur'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_translator',
            field=models.BooleanField(default=False, verbose_name='Traducteur'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_twitter',
            field=models.URLField(blank=True, verbose_name='Twitter / X'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_youtube',
            field=models.URLField(blank=True, verbose_name='YouTube'),
        ),
    ]
