# Generated by Django 5.2.10 on 2026-02-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_location_city_user_location_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Banni'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_admin',
            field=models.BooleanField(default=False, verbose_name='Administrateur'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_moderator',
            field=models.BooleanField(default=False, verbose_name='Modérateur'),
        ),
    ]
