# Generated by Django 5.2.10 on 2026-02-07 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_banned_user_role_admin_user_role_moderator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='badges/')),
                ('condition_type', models.CharField(choices=[('CHAPTERS_READ', 'Chapitres Lus'), ('SERIES_COMPLETED', 'Séries Terminées'), ('COMMENTS_POSTED', 'Commentaires Postés'), ('ACCOUNT_AGE', 'Ancienneté (Jours)'), ('GROUP_JOINED', 'Groupes Rejoints')], max_length=50)),
                ('threshold', models.PositiveIntegerField(help_text='Valeur cible pour débloquer (ex: 100 pour 100 chapitres)')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='xp',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
