# Generated by Django 5.2.10 on 2026-02-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_badge_alter_user_xp_userbadge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role_author',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role_editor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role_translator',
        ),
    ]
