# Generated by Django 5.2.10 on 2026-03-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_unused_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dnd_mode',
            field=models.BooleanField(default=False, verbose_name='Mode Ne Pas Déranger'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pref_notif_friends',
            field=models.BooleanField(default=True, verbose_name='Notifs Amis'),
        ),
        migrations.AddField(
            model_name='user',
            name='pref_notif_likes',
            field=models.BooleanField(default=True, verbose_name="Notifs J'aime"),
        ),
        migrations.AddField(
            model_name='user',
            name='pref_notif_messages',
            field=models.BooleanField(default=True, verbose_name='Notifs Messages'),
        ),
        migrations.AddField(
            model_name='user',
            name='pref_notif_replies',
            field=models.BooleanField(default=True, verbose_name='Notifs Réponses'),
        ),
    ]
