# Generated by Django 5.2.10 on 2026-03-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_dnd_mode_user_last_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_nsfw_access',
            field=models.BooleanField(default=False, verbose_name='Accès 18+'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Membre Gratuit'), ('premium', 'Abonné Premium'), ('legend', 'Membre Légende')], default='free', max_length=20),
        ),
    ]
