# Generated by Django 5.2.10 on 2026-04-09 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_has_nsfw_access_user_subscription_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age_verified',
            field=models.BooleanField(default=False, verbose_name='Âge Vérifié'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Est Premium'),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration Premium'),
        ),
        migrations.AddField(
            model_name='user',
            name='prestige_level',
            field=models.PositiveIntegerField(default=0, verbose_name='Niveau de Prestige'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_in_fiat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (Fiat)')),
                ('currency', models.CharField(default='XOF', max_length=10, verbose_name='Devise')),
                ('gateway_used', models.CharField(max_length=50, verbose_name='Passerelle de paiement')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Réussi'), ('FAILED', 'Échoué')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('credits_awarded', models.PositiveIntegerField(verbose_name='Crédits Accordés')),
                ('webhook_payload', models.JSONField(blank=True, null=True, verbose_name='Payload Webhook')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_balance', models.PositiveIntegerField(default=0, verbose_name='Solde de Crédits')),
                ('auto_use_credits', models.BooleanField(default=False, verbose_name='Utilisation auto des crédits')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
