# Generated by Django 5.2.10 on 2026-04-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_expires',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_type',
        ),
    ]
