# Generated by Django 5.2.10 on 2026-02-08 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_BAN', 'Bannissement Utilisateur'), ('USER_UNBAN', 'Débannissement Utilisateur'), ('USER_PROMOTE', 'Promotion Utilisateur'), ('USER_DEMOTE', 'Rétrogradation Utilisateur'), ('CONTENT_DELETE', 'Suppression Contenu'), ('GROUP_BAN', 'Bannissement Groupe'), ('GROUP_CLOSE', 'Fermeture Groupe'), ('GENRE_CREATE', 'Création Genre'), ('GENRE_UPDATE', 'Modification Genre'), ('SERIES_CREATE', 'Création Série'), ('SERIES_UPDATE', 'Modification Série'), ('CHAPTER_CREATE', 'Création Chapitre')], max_length=50, verbose_name='Action')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_performed', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_received', to=settings.AUTH_USER_MODEL, verbose_name='Cible (Utilisateur)')),
            ],
            options={
                'verbose_name': 'Log Système',
                'verbose_name_plural': 'Logs Système',
                'ordering': ['-created_at'],
            },
        ),
    ]
