# Generated by Django 5.2.10 on 2026-02-10 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkedUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('total_chunks', models.IntegerField()),
                ('received_chunks', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('uploading', 'En cours'), ('processing', 'Assemblage'), ('completed', 'Terminé'), ('failed', 'Échec')], default='uploading', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload par morceaux',
                'verbose_name_plural': 'Uploads par morceaux',
            },
        ),
    ]
