# Generated by Django 5.2.10 on 2026-02-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_chunkedupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkedupload',
            name='processed_files',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chunkedupload',
            name='total_files_to_process',
            field=models.IntegerField(default=0),
        ),
    ]
