# Generated by Django 5.2.10 on 2026-02-02 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.PositiveIntegerField(default=1, verbose_name='Page actuelle')),
                ('completed', models.BooleanField(default=False, verbose_name='Terminé')),
                ('last_read', models.DateTimeField(auto_now=True, verbose_name='Dernière lecture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='catalog.chapter', verbose_name='Chapitre')),
            ],
            options={
                'verbose_name': 'Progression de lecture',
                'verbose_name_plural': 'Progressions de lecture',
                'ordering': ['-last_read'],
            },
        ),
    ]
