# Generated by Django 5.2.10 on 2026-02-02 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Couverture')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Auteur')),
                ('artist', models.CharField(blank=True, max_length=200, verbose_name='Artiste')),
                ('status', models.CharField(choices=[('ongoing', 'En cours'), ('completed', 'Terminé'), ('hiatus', 'En pause')], default='ongoing', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Série',
                'verbose_name_plural': 'Séries',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Numéro')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='catalog.series', verbose_name='Série')),
            ],
            options={
                'verbose_name': 'Chapitre',
                'verbose_name_plural': 'Chapitres',
                'ordering': ['series', 'number'],
                'unique_together': {('series', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(verbose_name='Numéro de page')),
                ('image', models.ImageField(upload_to='mangas/%Y/%m/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='catalog.chapter', verbose_name='Chapitre')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['chapter', 'page_number'],
                'unique_together': {('chapter', 'page_number')},
            },
        ),
    ]
