# Generated by Django 5.2.10 on 2026-02-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='mangas/pdfs/', verbose_name='Fichier PDF'),
        ),
    ]
