# Generated by Django 5.2.10 on 2026-02-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_chapter_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de publication'),
        ),
    ]
