# Generated by Django 5.2.10 on 2026-02-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_series_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de vues'),
        ),
    ]
