# Generated by Django 5.2.10 on 2026-02-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='series',
            name='type',
            field=models.CharField(choices=[('manga', 'Manga'), ('manhwa', 'Manhwa'), ('manhua', 'Manhua'), ('novel', 'Novel'), ('webtoon', 'Webtoon')], default='manga', max_length=20, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='series',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='series', to='catalog.genre', verbose_name='Genres'),
        ),
    ]
