# Generated by Django 5.2.10 on 2026-02-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_genre_series_type_series_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='chapter',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='scans/', verbose_name='Fichier Source'),
        ),
    ]
