# Generated by Django 5.2.10 on 2026-02-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_chapter_pdf_file_chapter_source_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='updated_at',
        ),
    ]
