# Generated by Django 5.2.10 on 2026-02-18 12:02

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_chapter_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='source_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='scans/', verbose_name='Fichier Source'),
        ),
    ]
