# Generated by Django 5.2.10 on 2026-03-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='average_rating',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='Note moyenne'),
        ),
        migrations.AddField(
            model_name='series',
            name='chapters_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Nombre de chapitres'),
        ),
        migrations.AlterField(
            model_name='series',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Nombre de vues'),
        ),
    ]
