# Generated by Django 5.2.10 on 2026-03-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_series_average_rating_series_chapters_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='review_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name="Nombre d'avis"),
        ),
    ]
