# Generated by Django 5.2.10 on 2026-04-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_series_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Chapitre Premium'),
        ),
        migrations.AddField(
            model_name='series',
            name='nsfw',
            field=models.BooleanField(default=False, verbose_name='Contenu 18+ (NSFW)'),
        ),
    ]
