# Generated by Django 5.2.10 on 2026-02-04 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='social.group'),
        ),
    ]
