# Generated by Django 5.2.10 on 2026-03-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_message_likes_message_parent_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='background_color',
            field=models.CharField(default='#6c5ce7', max_length=7),
        ),
        migrations.AddField(
            model_name='story',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='forum/stories/backgrounds/'),
        ),
        migrations.AddField(
            model_name='story',
            name='node_type',
            field=models.CharField(choices=[('media', 'Image/Video Media'), ('text', 'Rich Text Block')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='story',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/'),
        ),
    ]
