# Generated by Django 5.2.10 on 2026-03-18 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_event_organizer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_dms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dm_replies', to='social.directmessage'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system', 'Système'), ('like', "J'aime"), ('reply', 'Réponse'), ('friend_request', "Demande d'ami"), ('friend_accept', 'Ami accepté'), ('message', 'Message Privé')], default='system', max_length=20),
        ),
    ]
